### PR TITLE
Added fallback for trimLeft using String.prototype

### PR DESCRIPTION
**Pull request by hampusohlsson**
`trimLeft()` is non-standard and implementation might diff between browsers. Was causing errors in IE, for example.

### CODE REVIEW

**Comment by fb55** [comment]
It doesn't really matter if `trimLeft` or `trim` is called, I would be fine with adding

```js
var trim = String.prototype.trimLeft || String.prototype.trim;
```

and later

```js
selector = trim.call(selector);
```

Extending native prototypes this way has side-effects (eg. the new property will be enumerated in `for in`-loops), which might break someones code.

**Comment by hampusohlsson** [comment]
Good points. I'll update the PR

**Comment by fb55** [comment]
@hampusohlsson I took this chance to do some internal restructuring, thank you for your effort & the report, though. I appreciate it.

**Comment by hampusohlsson** [comment]
No worries, glad to help.

**Pull request closed without merging**
